version: '3.8'

services:
  # Frontend
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api-gateway
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8080

  # API Gateway
  api-gateway:
    build:
      context: ./server/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server/api-gateway:/app
      - /app/node_modules
    depends_on:
      - identity-service
      - equipment-service
      - reservation-service
      - notification-service
    environment:
      - NODE_ENV=development
      - PORT=8080
      - IDENTITY_SERVICE_URL=http://identity-service:3001
      - EQUIPMENT_SERVICE_URL=http://equipment-service:3002
      - RESERVATION_SERVICE_URL=http://reservation-service:3003
      - NOTIFICATION_SERVICE_URL=http://notification-service:3004
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKER=kafka:9092

  # Identity Service
  identity-service:
    build:
      context: ./server/identity-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server/identity-service:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/identity_db
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret_key_here
      - KAFKA_BROKER=kafka:9092

  # Equipment Service
  equipment-service:
    build:
      context: ./server/equipment-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./server/equipment-service:/app
      - /app/node_modules
    depends_on:
      - postgres
      - kafka
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/equipment_db
      - KAFKA_BROKER=kafka:9092

  # Reservation Service
  reservation-service:
    build:
      context: ./server/reservation-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./server/reservation-service:/app
      - /app/node_modules
    depends_on:
      - postgres
      - kafka
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/reservation_db
      - KAFKA_BROKER=kafka:9092

  # Notification Service
  notification-service:
    build:
      context: ./server/notification-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    volumes:
      - ./server/notification-service:/app
      - /app/node_modules
    depends_on:
      - kafka
      - redis
    environment:
      - NODE_ENV=development
      - PORT=3004
      - KAFKA_BROKER=kafka:9092
      - REDIS_URL=redis://redis:6379

  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=identity_db,equipment_db,reservation_db

  # Redis for caching and session management
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Kafka for event streaming
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka
    depends_on:
      - zookeeper

  # Kafka UI for monitoring
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=open-science-kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
      - zookeeper

volumes:
  postgres_data:
  redis_data:
  zookeeper_data:
  kafka_data: 